### ISSUE TITLE
Opção 6 - Extrato

### ISSUE THREAD

**Issue by MarceloBoal** [ninj4skill/projeto4-cc2632#6]
Gera um arquivo com o histórico de todas as operações realizadas na conta, com valores, incluindo as tarifas.
Dados solicitados:

- [x] CPF
- [x] Senha

O formato do extrato é livre, porém o arquivo de saída deve ser em formato txt e que possa ser aberto em qualquer editor de texto.
Não é necessário armazenar as datas das transações
O extrato só pode ser exibido se o CPF e senha estiverem corretos

**Comment by Onabe142** [comment]
Feito
